# Generated by Django 4.2.6 on 2023-11-03 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datademoapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signupinfo',
            name='city',
        ),
        migrations.RemoveField(
            model_name='signupinfo',
            name='password',
        ),
    ]
