# Generated by Django 4.2.6 on 2023-11-03 10:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('datademoapp', '0002_remove_signupinfo_city_remove_signupinfo_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='signupinfo',
            name='DateofBirth',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='signupinfo',
            name='address',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='signupinfo',
            name='password',
            field=models.CharField(default=django.utils.timezone.now, max_length=12),
            preserve_default=False,
        ),
    ]
